name: run-tests

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [ ubuntu-latest, windows-latest ]
        include:
          # Laravel 11 mappings
          - laravel: 11.*
            php: 8.2
            testbench: ^9.0
            larastan: ^3.0
            stability: prefer-stable
          - laravel: 11.*
            php: 8.3
            testbench: ^9.0
            larastan: ^3.0
            stability: prefer-stable
          - laravel: 11.*
            php: 8.4
            testbench: ^9.0
            larastan: ^3.0
            stability: prefer-stable

          # Laravel 10 mappings
          - laravel: 10.*
            php: 8.1
            testbench: ^8.0
            larastan: ^2.0
            stability: prefer-lowest
          - laravel: 10.*
            php: 8.2
            testbench: ^8.0
            larastan: ^2.0
            stability: prefer-stable
          - laravel: 10.*
            php: 8.3
            testbench: ^8.0
            larastan: ^2.0
            stability: prefer-stable

    name: P${{ matrix.php }} - L${{ matrix.laravel }} - ${{ matrix.stability }} - ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, imagick, fileinfo
          coverage: none

      - name: Setup problem matchers
        run: |
          echo "::add-matcher::${{ runner.tool_cache }}/php.json"
          echo "::add-matcher::${{ runner.tool_cache }}/phpunit.json"

      - name: Install dependencies
        run: |
          composer require "laravel/framework:${{ matrix.laravel }}" "orchestra/testbench:${{ matrix.testbench }}" "larastan/larastan:${{ matrix.larastan }}" --no-interaction --no-update
          composer update --${{ matrix.stability }} --prefer-dist --no-interaction

      - name: Execute tests
        run: vendor/bin/phpunit
